name: gh-pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: gh-pages
      run: |
        #!/bin/bash
        # http://redsymbol.net/articles/unofficial-bash-strict-mode/
        set -euo pipefail
        IFS=$'\n\t'

        buildDirectory=build

        # # get a clean master branch assuming
        # git checkout nstarman-gh-pages
        # git pull origin nstarman-gh-pages
        # git clean -df
        # git checkout -- .
        # git fetch --all

        ls 
        cd docs
        ls

        # build html docs from sphinx files
        make clean

        # # create or use orphaned gh-pages branch
        # branch_name=gh-pages
        # if [ $(git branch --list "$branch_name") ]
        # then
        #   git stash
        #   git checkout $branch_name
        #   git pull origin $branch_name
        #   #git stash apply
        #   git checkout stash -- . # force git stash to overwrite added files
        # else
        #   git checkout --orphan "$branch_name"
        # fi

        # if [ -d "$buildDirectory" ]
        # then
        #   ls | grep -v _build | xargs rm -r
        #   mv build/* . && rm -rf build
        #   git add .
        #   git commit -m "new pages version $(date)"
        #   git push origin gh-pages
        #   # github.com recognizes gh-pages branch and create pages
        #   # url scheme https//:[github-handle].github.io/[repository]
        # else
        #   echo "directory $buildDirectory does not exists"
        # fi
